company_name = input("what is your company name?")
employee_number = input("How many Employees do you have?")
location = input("In which state are you located?")
policy_price = input("what is your lowest price for a policy?")
print(company_name)
print(employee_number)
print(location)
print(policy_price)
print(f"We are {company_name} located in {location}. Our {employee_number}  employees can help you find the policy that is right for you with policies {policy_price} per month!")